# Generated by Django 3.2.4 on 2021-11-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(default='555-555-555', max_length=30),
            preserve_default=False,
        ),
    ]
